# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          KIM JUN YOUNG
baseurl:        ""
url:            "https://kimjunyoung.com"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         KIM JUN YOUNG
  url:          https://kimjunyoung.com/
  email:        me@kimjunyoung.com
  github:       k1mjunyoung
  twitter:      

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/k1mjunyoung.github.io

plugins:
  - jekyll-toc