#fourth-place:
#- name: sixshop
#  role: Product Design Lead
#  date: 2021. APR - Current

fourth-place:
- name: SQL-INJECTION-SPRING
  sub: 모의 SQL인젝션 웹서비스
  date: 2023. 03 - 2023. 12
  url: https://github.com/k1mjunyoung/sql-injection-spring

third-place:
- name: K-water 대국민 물 빅데이터 공모전
  sub: 포스트 코로나 주요 관광지 수질 예측
  date: 2022. 04 - 2022. 07
  url: 

second-place:
- name: Qshing-detector
  sub: 큐싱 탐지 어플리케이션
  date: 2022. 03 - 2022. 12
  url: https://github.com/teamSCV/qshing-detector

first-place:
- name: 숭글(Soongle)
  sub: 교내 중고거래플랫폼
  date: 2018. 03 - 2024. 02
  url: https://github.com/k1mjunyoung/soongle-django